export const AUTH_SUCCESS = "AUTH_SUCCESS";
export const AUTH_FAIL = "AUTH_FAIL";
export const AUTH_CLEAN_UP = "CLEAN_UP";
export const AUTH_UPDATE_PROFILE_START = "AUTH_UPDATE_PROFILE_START";
export const AUTH_UPDATE_PROFILE_SUCCESS = "AUTH_UPDATE_PROFILE_SUCCESS";
export const AUTH_UPDATE_PROFILE_FAIL = "AUTH_UPDATE_PROFILE_FAIL";
export const AUTH_UPDATE_PASSWORD_START = "AUTH_UPDATE_PASSWORD_START";
export const AUTH_UPDATE_PASSWORD_SUCCESS = "AUTH_UPDATE_PASSWORD_SUCCESS";
export const AUTH_UPDATE_PASSWORD_FAIL = "AUTH_UPDATE_PASSWORD_FAIL";
export const AUTH_RECOVER_PASSWORD_START = "AUTH_RECOVER_PASSWORD_START";
export const AUTH_RECOVER_PASSWORD_SUCCESS = "AUTH_RECOVER_PASSWORD_SUCCESS";
export const AUTH_RECOVER_PASSWORD_FAIL = "AUTH_RECOVER_PASSWORD_FAIL";

export const ADD_STASH_SUCCESS = "ADD_STASH_SUCCESS";
export const ADD_STASH_FAIL = "ADD_STASH_FAIL";
export const DELETE_STASH_SUCCESS = "DELETE_STASH_SUCCESS";
export const DELETE_STASH_FAIL = "DELETE_STASH_FAIL";
export const MODIFY_STASH_SUCCESS = "MODIFY_STASH_SUCCESS";
export const MODIFY_STASH_FAIL = "MODIFY_STASH_FAIL";
export const STASH_CLEAN_UP = "STASH_CLEAN_UP";

export const ADD_ITEM_SUCCESS = "ADD_ITEM_SUCCESS";
export const ADD_ITEM_FAIL = "ADD_ITEM_FAIL";
export const MODIFY_ITEM_SUCCESS = "MODIFY_ITEM_SUCCESS";
export const MODIFY_ITEM_FAIL = "MODIFY_ITEM_FAIL";
export const DELETE_ITEM_SUCCESS = "DELETE_ITEM_SUCCESS";
export const DELETE_ITEM_FAIL = "DELETE_ITEM_FAIL";
